### ISSUE TITLE
Error when launching the app

### ISSUE THREAD

**Issue by Kashlikov** [aws-samples/amazon-bedrock-client-for-mac#21]
**Describe the bug**
Getting error when launching app

`The operation couldn’t be completed. (AwsCommonRuntimeKit.CommonRunTimeError error 0.)`

**To Reproduce**
1. Error appears immediately after app starts

**Expected behavior**

**Screenshots**
![Screenshot 2024-03-14 at 11 43 18](https://github.com/aws-samples/amazon-bedrock-client-for-mac/assets/11250064/aaf8d5c4-f2e8-4c5f-81e8-1e63302c5326)

**Desktop (please complete the following information):**
 - OS: macOS 13.6.5

**Comment by didhd** [comment]
@Kashlikov Could you check if credentials are valid? (Should be in ~/.aws/credentials file.)

**Comment by AntoniaSch** [comment]
I have the same problem with macOS 14.3.1.

**Comment by didhd** [comment]
@Kashlikov @AntoniaSch Regarding this issue, the app has been updated to v1.2.0. While the error is currently not reproducible, making it difficult to fix, if you still encounter the problem after the update, it would be greatly appreciated if you could share the logs from the Amazon Bedrock Client directory under your home directory. The logs may help the development team identify the root cause of the issue. We apologize for the inconvenience caused.
