### ISSUE TITLE
[FEATURE] AWS secrets config in application not load from system properties

### ISSUE THREAD

**Issue by ihoment-wangtaiping** [aws-samples/amazon-bedrock-client-for-mac#40]
I have two  AWS account one used for bedrock another used for other services.

Bedrock App load credentials from system properties that account i used for other services.

Did the Bedrock App load credentials in App not from system and i can config it myself.

**Comment by didhd** [comment]
@ihoment-wangtaiping The Bedrock application currently supports multiple AWS credential profiles in the settings. Would that not suffice for your need to configure AWS credentials within the application itself, rather than loading them from system properties? Please clarify if you require any additional functionality beyond the multi-profile support.

**Comment by ihoment-wangtaiping** [comment]
I found it! Thanks.
